client:
  open-dart:
    url: https://opendart.fss.or.kr/api
    key: 552fed265ebc64862d4399465f84bd16bf1a1c4e

scrapper:
  daily-stock-price:
    url: https://finance.naver.com/item/sise_day.naver?code=%s&page=%s




download:
  path: /Users/wkwon/Desktop
  file-path: /Users/wkwon/Desktop/CORPCODE.xml