spring:
  jpa:
    open-in-view: false
    hibernate.ddl-auto: create
    properties.hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 10000
  h2.console.enabled: true


datasource:
  core:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:test
    username: sa
    pool-name: core-db-pool
    data-source-properties:
      rewriteBatchedStatements: true

logging:
  level:
    org:
      springframework:
        jdbc: debug